### ISSUE TITLE
Components 

### ISSUE THREAD

**Issue by Rahul139-stack** [innovolve-ai/typerefinery-websight#18]
Components:
- Checkbox
- InputText
- RadioBox
- Password
- Text Area
- Button
    - Type
        - Submit
        - Reset
        - Button
    - Event
        - Label: typerefinery.ai/typerefinery/casemagment/save
- Dropdown
    - LIST
        - TEXT (key=value)

**Comment by wildone** [comment]
Please make these individual issues.

For form container it needs additional tickets to create FastAPI endpoint that talks to TMS. TMS needs a token to post to so it need to be treated as a secret.

**Comment by wildone** [comment]
@Rahul139-stack have we got individual tickets for theses?

**Comment by Rahul139-stack** [comment]
@wildone Yes ,most of the issues created. Thanks

**Comment by Harikarthyk** [comment]
Created all the components UI
