### ISSUE TITLE
Data Table Component

### ISSUE THREAD

**Issue by Rahul139-stack** [innovolve-ai/typerefinery-websight#28]
We create a data table with some static values.

However, the data table values are right now coming from vue values, which are mentioned in the vue instance object while mounting. We are unable to add values using any JS files.

**Vue instance code**
![image](https://user-images.githubusercontent.com/81350384/209764115-1936bdaf-753b-457b-98e1-b4441a4203d5.png)

**Datatable.html**
![image](https://user-images.githubusercontent.com/81350384/209764317-a44cfb4c-e246-4fe7-9b12-b4d8a1714c9a.png)

**Comment by Harikarthyk** [comment]
Same Problem as #29.

Since the values are coming from the Vue instance created, as of now they can not be edited on the fly.

**Comment by Harikarthyk** [comment]
Closing this issue, for the making, this dynamic created a separate issue.
Please refer: #78
