### ISSUE TITLE
Checkbox Component

### ISSUE THREAD

**Issue by Rahul139-stack** [innovolve-ai/typerefinery-websight#29]
We created a checkbox component.

But we are not able to control the inputs. Not able to make the checkbox functional as we need to v-model to interact.
Since Vue handles them, we could not handle them through our custom JS functions. 

We tried passing the values from the model(Java) to the v-model, but that did not work as expected.

**The HTML code for the checkbox is attached below.**

![image](https://user-images.githubusercontent.com/81350384/209767271-c28f020f-ed34-48d6-9150-613a5c391709.png)

**Comment by wildone** [comment]
@Rahul139-stack what next to try?

**Comment by Harikarthyk** [comment]
Able to make them functional with the help of DOM Events
