### ISSUE TITLE
 Input Field Component

### ISSUE THREAD

**Issue by Rahul139-stack** [innovolve-ai/typerefinery-websight#30]
We created an Input Field Component

But we are not able to control the inputs. 

Please refer to #29 

For now, for the Forms, we are now fetching the values from the DOM directly Eg. document.getElementById().value

But this is not the usual way for fetching values in Vue, although this is working, this is not suitable for Checkbox #29, and Radio Button #31.

**Comment by Harikarthyk** [comment]
Able to make them functional with the help of DOM Events
