### ISSUE TITLE
Bar Chart component

### ISSUE THREAD

**Issue by Rahul139-stack** [innovolve-ai/typerefinery-websight#41]
Create bar chart component #27 
 **Sample:**
![image](https://user-images.githubusercontent.com/81350384/210226023-5781002d-62e6-463d-a487-fb60c2d6c7f4.png)

**Comment by Harikarthyk** [comment]
Bar chart Component created as required using chart.js 

NOTE: Data can be mapped with JSON file. 

Author: @rohitgupta274509
