### ISSUE TITLE
Sidebar Component

### ISSUE THREAD

**Issue by Rahul139-stack** [innovolve-ai/typerefinery-websight#55]
Creating a Sidebar component using Prime vue.

**Sample Output**
<img width="297" alt="Screenshot 2023-01-06 at 11 37 33 AM" src="https://user-images.githubusercontent.com/54505967/210940766-eae55868-34e8-466c-ab14-813be5ffcd98.png">

**Comment by Rahul139-stack** [comment]
Created sidebar tree  as much same from drawio sidebar .
**Sample** :
![MicrosoftTeams-image (11)](https://user-images.githubusercontent.com/81350384/210703836-7daefcbb-bf69-4a86-8173-6bf7d915d7b9.png)

**Concern** :
- But there is issue that websight do not have sidebar space, while we are using maincontainer also and layouts, still there is 
-    space in left side of the page.
- If we use layouts, we could not drop another layouts on it.

**Comment by Harikarthyk** [comment]
We also created a discussion for the same in websight/starter repo.

Please refer to the following link:
https://github.com/websight-io/starter/discussions/113
